# MPLAB IDE generated this makefile for use with GNU make.
# Project: uart.mcp
# Date: Sat Mar 05 20:11:00 2011

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

16F883TEMP.cof : 16F883TEMP.o
	$(CC) /p16F883 "16F883TEMP.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"16F883TEMP.cof" /M"16F883TEMP.map" /W /x

16F883TEMP.o : 16F883TEMP.ASM ../../../../Program\ Files/Microchip/MPASM\ Suite/p16f883.inc
	$(AS) /q /p16F883 "16F883TEMP.ASM" /l"16F883TEMP.lst" /e"16F883TEMP.err" /d__DEBUG=1

clean : 
	$(CC) "16F883TEMP.o" "16F883TEMP.hex" "16F883TEMP.err" "16F883TEMP.lst" "16F883TEMP.cof"

