  ;MODIFICACION DE LA PALABRA DE CONFIGURACION DEL PIC, CON ESTO SE EVITA COMETER ERRORES EN
  ;LA PROGRAMACION DEL PIC (COMO PUEDE SER DEJAR EL CODIGO PROTEGIDO)
  __CONFIG _CONFIG1, _HS_OSC & _WDT_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF
  __CONFIG _CONFIG2, _WRT_OFF & _BOR40V
